/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppCompetitorsRouteImport } from './routes/app/competitors'
import { Route as AppContentRouteImport } from './routes/app/content'
import { Route as AppGbpRouteImport } from './routes/app/gbp'
import { Route as AppKeywordsRouteImport } from './routes/app/keywords'
import { Route as AppPublishRouteImport } from './routes/app/publish'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppVisibilityRouteImport } from './routes/app/visibility'
import { Route as AppContentIndexRouteImport } from './routes/app/content/index'
import { Route as AppContentArticleIdRouteImport } from './routes/app/content/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppGbpRoute = AppGbpRouteImport.update({
  id: '/gbp',
  path: '/gbp',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsRoute = AppKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVisibilityRoute = AppVisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContentRoute,
} as any)
const AppContentArticleIdRoute = AppContentArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AppContentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/content': typeof AppContentRouteWithChildren
  '/app/gbp': typeof AppGbpRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visibility': typeof AppVisibilityRoute
  '/app/': typeof AppIndexRoute
  '/app/content/$articleId': typeof AppContentArticleIdRoute
  '/app/content/': typeof AppContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/gbp': typeof AppGbpRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visibility': typeof AppVisibilityRoute
  '/app': typeof AppIndexRoute
  '/app/content/$articleId': typeof AppContentArticleIdRoute
  '/app/content': typeof AppContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/content': typeof AppContentRouteWithChildren
  '/app/gbp': typeof AppGbpRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visibility': typeof AppVisibilityRoute
  '/app/': typeof AppIndexRoute
  '/app/content/$articleId': typeof AppContentArticleIdRoute
  '/app/content/': typeof AppContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/setup'
    | '/app/calendar'
    | '/app/competitors'
    | '/app/content'
    | '/app/gbp'
    | '/app/keywords'
    | '/app/publish'
    | '/app/settings'
    | '/app/visibility'
    | '/app/'
    | '/app/content/$articleId'
    | '/app/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/app/calendar'
    | '/app/competitors'
    | '/app/gbp'
    | '/app/keywords'
    | '/app/publish'
    | '/app/settings'
    | '/app/visibility'
    | '/app'
    | '/app/content/$articleId'
    | '/app/content'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/setup'
    | '/app/calendar'
    | '/app/competitors'
    | '/app/content'
    | '/app/gbp'
    | '/app/keywords'
    | '/app/publish'
    | '/app/settings'
    | '/app/visibility'
    | '/app/'
    | '/app/content/$articleId'
    | '/app/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gbp': {
      id: '/app/gbp'
      path: '/gbp'
      fullPath: '/app/gbp'
      preLoaderRoute: typeof AppGbpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keywords': {
      id: '/app/keywords'
      path: '/keywords'
      fullPath: '/app/keywords'
      preLoaderRoute: typeof AppKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visibility': {
      id: '/app/visibility'
      path: '/visibility'
      fullPath: '/app/visibility'
      preLoaderRoute: typeof AppVisibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/': {
      id: '/app/content/'
      path: '/'
      fullPath: '/app/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppContentRoute
    }
    '/app/content/$articleId': {
      id: '/app/content/$articleId'
      path: '/$articleId'
      fullPath: '/app/content/$articleId'
      preLoaderRoute: typeof AppContentArticleIdRouteImport
      parentRoute: typeof AppContentRoute
    }
  }
}

interface AppContentRouteChildren {
  AppContentArticleIdRoute: typeof AppContentArticleIdRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
}

const AppContentRouteChildren: AppContentRouteChildren = {
  AppContentArticleIdRoute: AppContentArticleIdRoute,
  AppContentIndexRoute: AppContentIndexRoute,
}

const AppContentRouteWithChildren = AppContentRoute._addFileChildren(
  AppContentRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppContentRoute: typeof AppContentRouteWithChildren
  AppGbpRoute: typeof AppGbpRoute
  AppKeywordsRoute: typeof AppKeywordsRoute
  AppPublishRoute: typeof AppPublishRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVisibilityRoute: typeof AppVisibilityRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppContentRoute: AppContentRouteWithChildren,
  AppGbpRoute: AppGbpRoute,
  AppKeywordsRoute: AppKeywordsRoute,
  AppPublishRoute: AppPublishRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVisibilityRoute: AppVisibilityRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
